apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  template:
    spec:
      containers:
      - name: external-secrets
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://localstack.localstack.svc.cluster.local:4566"
