apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: localstack-secretstore
    kind: SecretStore
  target:
    name: my-app-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: my-app-secret
