apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secretstore
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: localstack-credentials
            key: secret-access-key
  conditions:
  - namespaces:
    - default
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
