{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eso-localstack.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.credentialsSecretName }}
            key: access-key-id
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.credentialsSecretName }}
            key: secret-access-key
  conditions:
  - namespaces:
    - {{ .Release.Namespace }}
  retrySettings:
    maxRetries: {{ .Values.secretStore.maxRetries }}
    retryInterval: {{ .Values.secretStore.retryInterval }}
{{- end }}
